---
title: "Project Classifier"
author: "Jean Lin"
date: "Tuesday, April 07, 2015"
output: html_document
---

# Donation Amount Trend of Random Projects
```{r, echo=FALSE}
proj.indices = sample(1:1581, 10, replace = FALSE)
```


The following figures show the trend of `r proj.indices` 

```{r, echo=FALSE}
library(ggplot2)

get.project.trend = function(proj.index, filepath){
    #order aid by published date
    dt.published.ordered = donationData[with(donationData, order(dt.published)), c("aid", "dt.published")]
    
    #get the start date of the donation event
    donation.details = read.csv(paste(filepath, dt.published.ordered[proj.index,"aid"], ".csv", sep=""), header = T, stringsAsFactors = F)
    
    donation.amount.daily = tapply(donation.details$Amount, donation.details$Date, sum)
    trend = data.frame(date = names(donation.amount.daily), total = donation.amount.daily)
    trend$date = as.Date(trend$date, "%Y/%m/%d")
    trend = trend[with(trend, order(date, decreasing = F)), ]
    trend
}

donationData = read.csv("df_adjusted.csv", fileEncoding = "UTF-8", stringsAsFactors = FALSE)

for(i in seq(proj.indices)){
    trend = get.project.trend(proj.indices[i], "./donation_details/")
    print(sum(trend$total))
    require(ggplot2)
    g = ggplot( data = trend, aes( date, total ))
    print(g + geom_point() +geom_line())
}
```

